{{- if and .Values.falco.enabled .Values.falco.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "falco.falco.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: falco
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.falco.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.falco.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.falco.serviceAccount.annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- include "falco.imagePullSecrets" . }}
{{- end }}
